mkdir BagMano
mkdir ManoCompress
mkdir ManoSlide
mkdir BoxMano
mkdir ManoDig
mkdir Overview
mkdir FingerAdduction
mkdir ManoLock
mkdir FingerExtension
mkdir ManoOrbit
mkdir FingerFlexion
mkdir ManoPoke
mkdir ThumbAduction
mkdir Fist
mkdir ManoPop
mkdir ThumbExtension
mkdir ManoSkreef
mkdir ThumbFlexion